name: AdvancedBooks
version: '${project.version}'
main: me.luucka.advancedbooks.AdvancedBooksPlugin
api-version: 1.18
softdepend: [ PlaceholderAPI ]
authors: [ LuuckA ]
description: Create minecraft books easily
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}
  - dev.jorel:commandapi-bukkit-shade:${libs.commandapi}
