name: AdvancedBooks
version: '${project.version}'
main: me.luucka.advancedbooks.AdvancedBooksPlugin
api-version: 1.18
softdepend: [ PlaceholderAPI ]
authors: [ LuuckA ]
description: Create minecraft books easily
libraries:
  - org.spongepowered:configurate-yaml:${configurate-yaml.version}
  - dev.jorel:commandapi-bukkit-shade:${commandapi.version}
